// Code generated by ent, DO NOT EDIT.

package ent

import (
	"ch24/fakes/adapters/sqlaite/ent/ingredient"
	"ch24/fakes/adapters/sqlaite/ent/pantry"
	"ch24/fakes/adapters/sqlaite/ent/recipeingredient"
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// IngredientCreate is the builder for creating a Ingredient entity.
type IngredientCreate struct {
	config
	mutation *IngredientMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetName sets the "name" field.
func (_c *IngredientCreate) SetName(v string) *IngredientCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetVegan sets the "vegan" field.
func (_c *IngredientCreate) SetVegan(v bool) *IngredientCreate {
	_c.mutation.SetVegan(v)
	return _c
}

// SetNillableVegan sets the "vegan" field if the given value is not nil.
func (_c *IngredientCreate) SetNillableVegan(v *bool) *IngredientCreate {
	if v != nil {
		_c.SetVegan(*v)
	}
	return _c
}

// SetPantryID sets the "pantry" edge to the Pantry entity by ID.
func (_c *IngredientCreate) SetPantryID(id int) *IngredientCreate {
	_c.mutation.SetPantryID(id)
	return _c
}

// SetNillablePantryID sets the "pantry" edge to the Pantry entity by ID if the given value is not nil.
func (_c *IngredientCreate) SetNillablePantryID(id *int) *IngredientCreate {
	if id != nil {
		_c = _c.SetPantryID(*id)
	}
	return _c
}

// SetPantry sets the "pantry" edge to the Pantry entity.
func (_c *IngredientCreate) SetPantry(v *Pantry) *IngredientCreate {
	return _c.SetPantryID(v.ID)
}

// AddRecipeingredientIDs adds the "recipeingredient" edge to the RecipeIngredient entity by IDs.
func (_c *IngredientCreate) AddRecipeingredientIDs(ids ...int) *IngredientCreate {
	_c.mutation.AddRecipeingredientIDs(ids...)
	return _c
}

// AddRecipeingredient adds the "recipeingredient" edges to the RecipeIngredient entity.
func (_c *IngredientCreate) AddRecipeingredient(v ...*RecipeIngredient) *IngredientCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddRecipeingredientIDs(ids...)
}

// Mutation returns the IngredientMutation object of the builder.
func (_c *IngredientCreate) Mutation() *IngredientMutation {
	return _c.mutation
}

// Save creates the Ingredient in the database.
func (_c *IngredientCreate) Save(ctx context.Context) (*Ingredient, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *IngredientCreate) SaveX(ctx context.Context) *Ingredient {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *IngredientCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *IngredientCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *IngredientCreate) defaults() {
	if _, ok := _c.mutation.Vegan(); !ok {
		v := ingredient.DefaultVegan
		_c.mutation.SetVegan(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *IngredientCreate) check() error {
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Ingredient.name"`)}
	}
	if _, ok := _c.mutation.Vegan(); !ok {
		return &ValidationError{Name: "vegan", err: errors.New(`ent: missing required field "Ingredient.vegan"`)}
	}
	return nil
}

func (_c *IngredientCreate) sqlSave(ctx context.Context) (*Ingredient, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *IngredientCreate) createSpec() (*Ingredient, *sqlgraph.CreateSpec) {
	var (
		_node = &Ingredient{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(ingredient.Table, sqlgraph.NewFieldSpec(ingredient.FieldID, field.TypeInt))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(ingredient.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Vegan(); ok {
		_spec.SetField(ingredient.FieldVegan, field.TypeBool, value)
		_node.Vegan = value
	}
	if nodes := _c.mutation.PantryIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   ingredient.PantryTable,
			Columns: []string{ingredient.PantryColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(pantry.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.pantry_ingredient = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.RecipeingredientIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   ingredient.RecipeingredientTable,
			Columns: ingredient.RecipeingredientPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(recipeingredient.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Ingredient.Create().
//		SetName(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.IngredientUpsert) {
//			SetName(v+v).
//		}).
//		Exec(ctx)
func (_c *IngredientCreate) OnConflict(opts ...sql.ConflictOption) *IngredientUpsertOne {
	_c.conflict = opts
	return &IngredientUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Ingredient.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *IngredientCreate) OnConflictColumns(columns ...string) *IngredientUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &IngredientUpsertOne{
		create: _c,
	}
}

type (
	// IngredientUpsertOne is the builder for "upsert"-ing
	//  one Ingredient node.
	IngredientUpsertOne struct {
		create *IngredientCreate
	}

	// IngredientUpsert is the "OnConflict" setter.
	IngredientUpsert struct {
		*sql.UpdateSet
	}
)

// SetName sets the "name" field.
func (u *IngredientUpsert) SetName(v string) *IngredientUpsert {
	u.Set(ingredient.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *IngredientUpsert) UpdateName() *IngredientUpsert {
	u.SetExcluded(ingredient.FieldName)
	return u
}

// SetVegan sets the "vegan" field.
func (u *IngredientUpsert) SetVegan(v bool) *IngredientUpsert {
	u.Set(ingredient.FieldVegan, v)
	return u
}

// UpdateVegan sets the "vegan" field to the value that was provided on create.
func (u *IngredientUpsert) UpdateVegan() *IngredientUpsert {
	u.SetExcluded(ingredient.FieldVegan)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.Ingredient.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *IngredientUpsertOne) UpdateNewValues() *IngredientUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Ingredient.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *IngredientUpsertOne) Ignore() *IngredientUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *IngredientUpsertOne) DoNothing() *IngredientUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the IngredientCreate.OnConflict
// documentation for more info.
func (u *IngredientUpsertOne) Update(set func(*IngredientUpsert)) *IngredientUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&IngredientUpsert{UpdateSet: update})
	}))
	return u
}

// SetName sets the "name" field.
func (u *IngredientUpsertOne) SetName(v string) *IngredientUpsertOne {
	return u.Update(func(s *IngredientUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *IngredientUpsertOne) UpdateName() *IngredientUpsertOne {
	return u.Update(func(s *IngredientUpsert) {
		s.UpdateName()
	})
}

// SetVegan sets the "vegan" field.
func (u *IngredientUpsertOne) SetVegan(v bool) *IngredientUpsertOne {
	return u.Update(func(s *IngredientUpsert) {
		s.SetVegan(v)
	})
}

// UpdateVegan sets the "vegan" field to the value that was provided on create.
func (u *IngredientUpsertOne) UpdateVegan() *IngredientUpsertOne {
	return u.Update(func(s *IngredientUpsert) {
		s.UpdateVegan()
	})
}

// Exec executes the query.
func (u *IngredientUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for IngredientCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *IngredientUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *IngredientUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *IngredientUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// IngredientCreateBulk is the builder for creating many Ingredient entities in bulk.
type IngredientCreateBulk struct {
	config
	err      error
	builders []*IngredientCreate
	conflict []sql.ConflictOption
}

// Save creates the Ingredient entities in the database.
func (_c *IngredientCreateBulk) Save(ctx context.Context) ([]*Ingredient, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Ingredient, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*IngredientMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *IngredientCreateBulk) SaveX(ctx context.Context) []*Ingredient {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *IngredientCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *IngredientCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Ingredient.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.IngredientUpsert) {
//			SetName(v+v).
//		}).
//		Exec(ctx)
func (_c *IngredientCreateBulk) OnConflict(opts ...sql.ConflictOption) *IngredientUpsertBulk {
	_c.conflict = opts
	return &IngredientUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Ingredient.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *IngredientCreateBulk) OnConflictColumns(columns ...string) *IngredientUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &IngredientUpsertBulk{
		create: _c,
	}
}

// IngredientUpsertBulk is the builder for "upsert"-ing
// a bulk of Ingredient nodes.
type IngredientUpsertBulk struct {
	create *IngredientCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Ingredient.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *IngredientUpsertBulk) UpdateNewValues() *IngredientUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Ingredient.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *IngredientUpsertBulk) Ignore() *IngredientUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *IngredientUpsertBulk) DoNothing() *IngredientUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the IngredientCreateBulk.OnConflict
// documentation for more info.
func (u *IngredientUpsertBulk) Update(set func(*IngredientUpsert)) *IngredientUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&IngredientUpsert{UpdateSet: update})
	}))
	return u
}

// SetName sets the "name" field.
func (u *IngredientUpsertBulk) SetName(v string) *IngredientUpsertBulk {
	return u.Update(func(s *IngredientUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *IngredientUpsertBulk) UpdateName() *IngredientUpsertBulk {
	return u.Update(func(s *IngredientUpsert) {
		s.UpdateName()
	})
}

// SetVegan sets the "vegan" field.
func (u *IngredientUpsertBulk) SetVegan(v bool) *IngredientUpsertBulk {
	return u.Update(func(s *IngredientUpsert) {
		s.SetVegan(v)
	})
}

// UpdateVegan sets the "vegan" field to the value that was provided on create.
func (u *IngredientUpsertBulk) UpdateVegan() *IngredientUpsertBulk {
	return u.Update(func(s *IngredientUpsert) {
		s.UpdateVegan()
	})
}

// Exec executes the query.
func (u *IngredientUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the IngredientCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for IngredientCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *IngredientUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
