// Code generated by ent, DO NOT EDIT.

package ent

import (
	"ch24/fakes/adapters/sqlaite/ent/ingredient"
	"ch24/fakes/adapters/sqlaite/ent/pantry"
	"ch24/fakes/adapters/sqlaite/ent/predicate"
	"ch24/fakes/adapters/sqlaite/ent/recipeingredient"
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// IngredientUpdate is the builder for updating Ingredient entities.
type IngredientUpdate struct {
	config
	hooks    []Hook
	mutation *IngredientMutation
}

// Where appends a list predicates to the IngredientUpdate builder.
func (_u *IngredientUpdate) Where(ps ...predicate.Ingredient) *IngredientUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *IngredientUpdate) SetName(v string) *IngredientUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *IngredientUpdate) SetNillableName(v *string) *IngredientUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetVegan sets the "vegan" field.
func (_u *IngredientUpdate) SetVegan(v bool) *IngredientUpdate {
	_u.mutation.SetVegan(v)
	return _u
}

// SetNillableVegan sets the "vegan" field if the given value is not nil.
func (_u *IngredientUpdate) SetNillableVegan(v *bool) *IngredientUpdate {
	if v != nil {
		_u.SetVegan(*v)
	}
	return _u
}

// SetPantryID sets the "pantry" edge to the Pantry entity by ID.
func (_u *IngredientUpdate) SetPantryID(id int) *IngredientUpdate {
	_u.mutation.SetPantryID(id)
	return _u
}

// SetNillablePantryID sets the "pantry" edge to the Pantry entity by ID if the given value is not nil.
func (_u *IngredientUpdate) SetNillablePantryID(id *int) *IngredientUpdate {
	if id != nil {
		_u = _u.SetPantryID(*id)
	}
	return _u
}

// SetPantry sets the "pantry" edge to the Pantry entity.
func (_u *IngredientUpdate) SetPantry(v *Pantry) *IngredientUpdate {
	return _u.SetPantryID(v.ID)
}

// AddRecipeingredientIDs adds the "recipeingredient" edge to the RecipeIngredient entity by IDs.
func (_u *IngredientUpdate) AddRecipeingredientIDs(ids ...int) *IngredientUpdate {
	_u.mutation.AddRecipeingredientIDs(ids...)
	return _u
}

// AddRecipeingredient adds the "recipeingredient" edges to the RecipeIngredient entity.
func (_u *IngredientUpdate) AddRecipeingredient(v ...*RecipeIngredient) *IngredientUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddRecipeingredientIDs(ids...)
}

// Mutation returns the IngredientMutation object of the builder.
func (_u *IngredientUpdate) Mutation() *IngredientMutation {
	return _u.mutation
}

// ClearPantry clears the "pantry" edge to the Pantry entity.
func (_u *IngredientUpdate) ClearPantry() *IngredientUpdate {
	_u.mutation.ClearPantry()
	return _u
}

// ClearRecipeingredient clears all "recipeingredient" edges to the RecipeIngredient entity.
func (_u *IngredientUpdate) ClearRecipeingredient() *IngredientUpdate {
	_u.mutation.ClearRecipeingredient()
	return _u
}

// RemoveRecipeingredientIDs removes the "recipeingredient" edge to RecipeIngredient entities by IDs.
func (_u *IngredientUpdate) RemoveRecipeingredientIDs(ids ...int) *IngredientUpdate {
	_u.mutation.RemoveRecipeingredientIDs(ids...)
	return _u
}

// RemoveRecipeingredient removes "recipeingredient" edges to RecipeIngredient entities.
func (_u *IngredientUpdate) RemoveRecipeingredient(v ...*RecipeIngredient) *IngredientUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveRecipeingredientIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *IngredientUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *IngredientUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *IngredientUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *IngredientUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *IngredientUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(ingredient.Table, ingredient.Columns, sqlgraph.NewFieldSpec(ingredient.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(ingredient.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Vegan(); ok {
		_spec.SetField(ingredient.FieldVegan, field.TypeBool, value)
	}
	if _u.mutation.PantryCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   ingredient.PantryTable,
			Columns: []string{ingredient.PantryColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(pantry.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PantryIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   ingredient.PantryTable,
			Columns: []string{ingredient.PantryColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(pantry.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.RecipeingredientCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   ingredient.RecipeingredientTable,
			Columns: ingredient.RecipeingredientPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(recipeingredient.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedRecipeingredientIDs(); len(nodes) > 0 && !_u.mutation.RecipeingredientCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   ingredient.RecipeingredientTable,
			Columns: ingredient.RecipeingredientPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(recipeingredient.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RecipeingredientIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   ingredient.RecipeingredientTable,
			Columns: ingredient.RecipeingredientPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(recipeingredient.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{ingredient.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// IngredientUpdateOne is the builder for updating a single Ingredient entity.
type IngredientUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *IngredientMutation
}

// SetName sets the "name" field.
func (_u *IngredientUpdateOne) SetName(v string) *IngredientUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *IngredientUpdateOne) SetNillableName(v *string) *IngredientUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetVegan sets the "vegan" field.
func (_u *IngredientUpdateOne) SetVegan(v bool) *IngredientUpdateOne {
	_u.mutation.SetVegan(v)
	return _u
}

// SetNillableVegan sets the "vegan" field if the given value is not nil.
func (_u *IngredientUpdateOne) SetNillableVegan(v *bool) *IngredientUpdateOne {
	if v != nil {
		_u.SetVegan(*v)
	}
	return _u
}

// SetPantryID sets the "pantry" edge to the Pantry entity by ID.
func (_u *IngredientUpdateOne) SetPantryID(id int) *IngredientUpdateOne {
	_u.mutation.SetPantryID(id)
	return _u
}

// SetNillablePantryID sets the "pantry" edge to the Pantry entity by ID if the given value is not nil.
func (_u *IngredientUpdateOne) SetNillablePantryID(id *int) *IngredientUpdateOne {
	if id != nil {
		_u = _u.SetPantryID(*id)
	}
	return _u
}

// SetPantry sets the "pantry" edge to the Pantry entity.
func (_u *IngredientUpdateOne) SetPantry(v *Pantry) *IngredientUpdateOne {
	return _u.SetPantryID(v.ID)
}

// AddRecipeingredientIDs adds the "recipeingredient" edge to the RecipeIngredient entity by IDs.
func (_u *IngredientUpdateOne) AddRecipeingredientIDs(ids ...int) *IngredientUpdateOne {
	_u.mutation.AddRecipeingredientIDs(ids...)
	return _u
}

// AddRecipeingredient adds the "recipeingredient" edges to the RecipeIngredient entity.
func (_u *IngredientUpdateOne) AddRecipeingredient(v ...*RecipeIngredient) *IngredientUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddRecipeingredientIDs(ids...)
}

// Mutation returns the IngredientMutation object of the builder.
func (_u *IngredientUpdateOne) Mutation() *IngredientMutation {
	return _u.mutation
}

// ClearPantry clears the "pantry" edge to the Pantry entity.
func (_u *IngredientUpdateOne) ClearPantry() *IngredientUpdateOne {
	_u.mutation.ClearPantry()
	return _u
}

// ClearRecipeingredient clears all "recipeingredient" edges to the RecipeIngredient entity.
func (_u *IngredientUpdateOne) ClearRecipeingredient() *IngredientUpdateOne {
	_u.mutation.ClearRecipeingredient()
	return _u
}

// RemoveRecipeingredientIDs removes the "recipeingredient" edge to RecipeIngredient entities by IDs.
func (_u *IngredientUpdateOne) RemoveRecipeingredientIDs(ids ...int) *IngredientUpdateOne {
	_u.mutation.RemoveRecipeingredientIDs(ids...)
	return _u
}

// RemoveRecipeingredient removes "recipeingredient" edges to RecipeIngredient entities.
func (_u *IngredientUpdateOne) RemoveRecipeingredient(v ...*RecipeIngredient) *IngredientUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveRecipeingredientIDs(ids...)
}

// Where appends a list predicates to the IngredientUpdate builder.
func (_u *IngredientUpdateOne) Where(ps ...predicate.Ingredient) *IngredientUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *IngredientUpdateOne) Select(field string, fields ...string) *IngredientUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Ingredient entity.
func (_u *IngredientUpdateOne) Save(ctx context.Context) (*Ingredient, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *IngredientUpdateOne) SaveX(ctx context.Context) *Ingredient {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *IngredientUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *IngredientUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *IngredientUpdateOne) sqlSave(ctx context.Context) (_node *Ingredient, err error) {
	_spec := sqlgraph.NewUpdateSpec(ingredient.Table, ingredient.Columns, sqlgraph.NewFieldSpec(ingredient.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Ingredient.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, ingredient.FieldID)
		for _, f := range fields {
			if !ingredient.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != ingredient.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(ingredient.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Vegan(); ok {
		_spec.SetField(ingredient.FieldVegan, field.TypeBool, value)
	}
	if _u.mutation.PantryCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   ingredient.PantryTable,
			Columns: []string{ingredient.PantryColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(pantry.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PantryIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   ingredient.PantryTable,
			Columns: []string{ingredient.PantryColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(pantry.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.RecipeingredientCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   ingredient.RecipeingredientTable,
			Columns: ingredient.RecipeingredientPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(recipeingredient.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedRecipeingredientIDs(); len(nodes) > 0 && !_u.mutation.RecipeingredientCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   ingredient.RecipeingredientTable,
			Columns: ingredient.RecipeingredientPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(recipeingredient.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RecipeingredientIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   ingredient.RecipeingredientTable,
			Columns: ingredient.RecipeingredientPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(recipeingredient.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Ingredient{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{ingredient.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
