// Code generated by ent, DO NOT EDIT.

package ent

import (
	"ch24/fakes/adapters/sqlaite/ent/ingredient"
	"ch24/fakes/adapters/sqlaite/ent/pantry"
	"ch24/fakes/adapters/sqlaite/ent/predicate"
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// PantryUpdate is the builder for updating Pantry entities.
type PantryUpdate struct {
	config
	hooks    []Hook
	mutation *PantryMutation
}

// Where appends a list predicates to the PantryUpdate builder.
func (_u *PantryUpdate) Where(ps ...predicate.Pantry) *PantryUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetQuantity sets the "quantity" field.
func (_u *PantryUpdate) SetQuantity(v int) *PantryUpdate {
	_u.mutation.ResetQuantity()
	_u.mutation.SetQuantity(v)
	return _u
}

// SetNillableQuantity sets the "quantity" field if the given value is not nil.
func (_u *PantryUpdate) SetNillableQuantity(v *int) *PantryUpdate {
	if v != nil {
		_u.SetQuantity(*v)
	}
	return _u
}

// AddQuantity adds value to the "quantity" field.
func (_u *PantryUpdate) AddQuantity(v int) *PantryUpdate {
	_u.mutation.AddQuantity(v)
	return _u
}

// SetIngredientID sets the "ingredient" edge to the Ingredient entity by ID.
func (_u *PantryUpdate) SetIngredientID(id int) *PantryUpdate {
	_u.mutation.SetIngredientID(id)
	return _u
}

// SetNillableIngredientID sets the "ingredient" edge to the Ingredient entity by ID if the given value is not nil.
func (_u *PantryUpdate) SetNillableIngredientID(id *int) *PantryUpdate {
	if id != nil {
		_u = _u.SetIngredientID(*id)
	}
	return _u
}

// SetIngredient sets the "ingredient" edge to the Ingredient entity.
func (_u *PantryUpdate) SetIngredient(v *Ingredient) *PantryUpdate {
	return _u.SetIngredientID(v.ID)
}

// Mutation returns the PantryMutation object of the builder.
func (_u *PantryUpdate) Mutation() *PantryMutation {
	return _u.mutation
}

// ClearIngredient clears the "ingredient" edge to the Ingredient entity.
func (_u *PantryUpdate) ClearIngredient() *PantryUpdate {
	_u.mutation.ClearIngredient()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *PantryUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PantryUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *PantryUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PantryUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *PantryUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(pantry.Table, pantry.Columns, sqlgraph.NewFieldSpec(pantry.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Quantity(); ok {
		_spec.SetField(pantry.FieldQuantity, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedQuantity(); ok {
		_spec.AddField(pantry.FieldQuantity, field.TypeInt, value)
	}
	if _u.mutation.IngredientCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   pantry.IngredientTable,
			Columns: []string{pantry.IngredientColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ingredient.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.IngredientIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   pantry.IngredientTable,
			Columns: []string{pantry.IngredientColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ingredient.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{pantry.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// PantryUpdateOne is the builder for updating a single Pantry entity.
type PantryUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PantryMutation
}

// SetQuantity sets the "quantity" field.
func (_u *PantryUpdateOne) SetQuantity(v int) *PantryUpdateOne {
	_u.mutation.ResetQuantity()
	_u.mutation.SetQuantity(v)
	return _u
}

// SetNillableQuantity sets the "quantity" field if the given value is not nil.
func (_u *PantryUpdateOne) SetNillableQuantity(v *int) *PantryUpdateOne {
	if v != nil {
		_u.SetQuantity(*v)
	}
	return _u
}

// AddQuantity adds value to the "quantity" field.
func (_u *PantryUpdateOne) AddQuantity(v int) *PantryUpdateOne {
	_u.mutation.AddQuantity(v)
	return _u
}

// SetIngredientID sets the "ingredient" edge to the Ingredient entity by ID.
func (_u *PantryUpdateOne) SetIngredientID(id int) *PantryUpdateOne {
	_u.mutation.SetIngredientID(id)
	return _u
}

// SetNillableIngredientID sets the "ingredient" edge to the Ingredient entity by ID if the given value is not nil.
func (_u *PantryUpdateOne) SetNillableIngredientID(id *int) *PantryUpdateOne {
	if id != nil {
		_u = _u.SetIngredientID(*id)
	}
	return _u
}

// SetIngredient sets the "ingredient" edge to the Ingredient entity.
func (_u *PantryUpdateOne) SetIngredient(v *Ingredient) *PantryUpdateOne {
	return _u.SetIngredientID(v.ID)
}

// Mutation returns the PantryMutation object of the builder.
func (_u *PantryUpdateOne) Mutation() *PantryMutation {
	return _u.mutation
}

// ClearIngredient clears the "ingredient" edge to the Ingredient entity.
func (_u *PantryUpdateOne) ClearIngredient() *PantryUpdateOne {
	_u.mutation.ClearIngredient()
	return _u
}

// Where appends a list predicates to the PantryUpdate builder.
func (_u *PantryUpdateOne) Where(ps ...predicate.Pantry) *PantryUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *PantryUpdateOne) Select(field string, fields ...string) *PantryUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Pantry entity.
func (_u *PantryUpdateOne) Save(ctx context.Context) (*Pantry, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PantryUpdateOne) SaveX(ctx context.Context) *Pantry {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *PantryUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PantryUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *PantryUpdateOne) sqlSave(ctx context.Context) (_node *Pantry, err error) {
	_spec := sqlgraph.NewUpdateSpec(pantry.Table, pantry.Columns, sqlgraph.NewFieldSpec(pantry.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Pantry.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, pantry.FieldID)
		for _, f := range fields {
			if !pantry.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != pantry.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Quantity(); ok {
		_spec.SetField(pantry.FieldQuantity, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedQuantity(); ok {
		_spec.AddField(pantry.FieldQuantity, field.TypeInt, value)
	}
	if _u.mutation.IngredientCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   pantry.IngredientTable,
			Columns: []string{pantry.IngredientColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ingredient.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.IngredientIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   pantry.IngredientTable,
			Columns: []string{pantry.IngredientColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ingredient.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Pantry{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{pantry.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
