// Code generated by ent, DO NOT EDIT.

package ent

import (
	"ch24/fakes/adapters/sqlaite/ent/predicate"
	"ch24/fakes/adapters/sqlaite/ent/recipe"
	"ch24/fakes/adapters/sqlaite/ent/recipeingredient"
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// RecipeUpdate is the builder for updating Recipe entities.
type RecipeUpdate struct {
	config
	hooks    []Hook
	mutation *RecipeMutation
}

// Where appends a list predicates to the RecipeUpdate builder.
func (_u *RecipeUpdate) Where(ps ...predicate.Recipe) *RecipeUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *RecipeUpdate) SetName(v string) *RecipeUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *RecipeUpdate) SetNillableName(v *string) *RecipeUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *RecipeUpdate) SetDescription(v string) *RecipeUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *RecipeUpdate) SetNillableDescription(v *string) *RecipeUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// SetMealType sets the "meal_type" field.
func (_u *RecipeUpdate) SetMealType(v int) *RecipeUpdate {
	_u.mutation.ResetMealType()
	_u.mutation.SetMealType(v)
	return _u
}

// SetNillableMealType sets the "meal_type" field if the given value is not nil.
func (_u *RecipeUpdate) SetNillableMealType(v *int) *RecipeUpdate {
	if v != nil {
		_u.SetMealType(*v)
	}
	return _u
}

// AddMealType adds value to the "meal_type" field.
func (_u *RecipeUpdate) AddMealType(v int) *RecipeUpdate {
	_u.mutation.AddMealType(v)
	return _u
}

// AddRecipeingredientIDs adds the "recipeingredient" edge to the RecipeIngredient entity by IDs.
func (_u *RecipeUpdate) AddRecipeingredientIDs(ids ...int) *RecipeUpdate {
	_u.mutation.AddRecipeingredientIDs(ids...)
	return _u
}

// AddRecipeingredient adds the "recipeingredient" edges to the RecipeIngredient entity.
func (_u *RecipeUpdate) AddRecipeingredient(v ...*RecipeIngredient) *RecipeUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddRecipeingredientIDs(ids...)
}

// Mutation returns the RecipeMutation object of the builder.
func (_u *RecipeUpdate) Mutation() *RecipeMutation {
	return _u.mutation
}

// ClearRecipeingredient clears all "recipeingredient" edges to the RecipeIngredient entity.
func (_u *RecipeUpdate) ClearRecipeingredient() *RecipeUpdate {
	_u.mutation.ClearRecipeingredient()
	return _u
}

// RemoveRecipeingredientIDs removes the "recipeingredient" edge to RecipeIngredient entities by IDs.
func (_u *RecipeUpdate) RemoveRecipeingredientIDs(ids ...int) *RecipeUpdate {
	_u.mutation.RemoveRecipeingredientIDs(ids...)
	return _u
}

// RemoveRecipeingredient removes "recipeingredient" edges to RecipeIngredient entities.
func (_u *RecipeUpdate) RemoveRecipeingredient(v ...*RecipeIngredient) *RecipeUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveRecipeingredientIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *RecipeUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RecipeUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *RecipeUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RecipeUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *RecipeUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(recipe.Table, recipe.Columns, sqlgraph.NewFieldSpec(recipe.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(recipe.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(recipe.FieldDescription, field.TypeString, value)
	}
	if value, ok := _u.mutation.MealType(); ok {
		_spec.SetField(recipe.FieldMealType, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMealType(); ok {
		_spec.AddField(recipe.FieldMealType, field.TypeInt, value)
	}
	if _u.mutation.RecipeingredientCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   recipe.RecipeingredientTable,
			Columns: []string{recipe.RecipeingredientColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(recipeingredient.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedRecipeingredientIDs(); len(nodes) > 0 && !_u.mutation.RecipeingredientCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   recipe.RecipeingredientTable,
			Columns: []string{recipe.RecipeingredientColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(recipeingredient.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RecipeingredientIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   recipe.RecipeingredientTable,
			Columns: []string{recipe.RecipeingredientColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(recipeingredient.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{recipe.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// RecipeUpdateOne is the builder for updating a single Recipe entity.
type RecipeUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *RecipeMutation
}

// SetName sets the "name" field.
func (_u *RecipeUpdateOne) SetName(v string) *RecipeUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *RecipeUpdateOne) SetNillableName(v *string) *RecipeUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *RecipeUpdateOne) SetDescription(v string) *RecipeUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *RecipeUpdateOne) SetNillableDescription(v *string) *RecipeUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// SetMealType sets the "meal_type" field.
func (_u *RecipeUpdateOne) SetMealType(v int) *RecipeUpdateOne {
	_u.mutation.ResetMealType()
	_u.mutation.SetMealType(v)
	return _u
}

// SetNillableMealType sets the "meal_type" field if the given value is not nil.
func (_u *RecipeUpdateOne) SetNillableMealType(v *int) *RecipeUpdateOne {
	if v != nil {
		_u.SetMealType(*v)
	}
	return _u
}

// AddMealType adds value to the "meal_type" field.
func (_u *RecipeUpdateOne) AddMealType(v int) *RecipeUpdateOne {
	_u.mutation.AddMealType(v)
	return _u
}

// AddRecipeingredientIDs adds the "recipeingredient" edge to the RecipeIngredient entity by IDs.
func (_u *RecipeUpdateOne) AddRecipeingredientIDs(ids ...int) *RecipeUpdateOne {
	_u.mutation.AddRecipeingredientIDs(ids...)
	return _u
}

// AddRecipeingredient adds the "recipeingredient" edges to the RecipeIngredient entity.
func (_u *RecipeUpdateOne) AddRecipeingredient(v ...*RecipeIngredient) *RecipeUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddRecipeingredientIDs(ids...)
}

// Mutation returns the RecipeMutation object of the builder.
func (_u *RecipeUpdateOne) Mutation() *RecipeMutation {
	return _u.mutation
}

// ClearRecipeingredient clears all "recipeingredient" edges to the RecipeIngredient entity.
func (_u *RecipeUpdateOne) ClearRecipeingredient() *RecipeUpdateOne {
	_u.mutation.ClearRecipeingredient()
	return _u
}

// RemoveRecipeingredientIDs removes the "recipeingredient" edge to RecipeIngredient entities by IDs.
func (_u *RecipeUpdateOne) RemoveRecipeingredientIDs(ids ...int) *RecipeUpdateOne {
	_u.mutation.RemoveRecipeingredientIDs(ids...)
	return _u
}

// RemoveRecipeingredient removes "recipeingredient" edges to RecipeIngredient entities.
func (_u *RecipeUpdateOne) RemoveRecipeingredient(v ...*RecipeIngredient) *RecipeUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveRecipeingredientIDs(ids...)
}

// Where appends a list predicates to the RecipeUpdate builder.
func (_u *RecipeUpdateOne) Where(ps ...predicate.Recipe) *RecipeUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *RecipeUpdateOne) Select(field string, fields ...string) *RecipeUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Recipe entity.
func (_u *RecipeUpdateOne) Save(ctx context.Context) (*Recipe, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RecipeUpdateOne) SaveX(ctx context.Context) *Recipe {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *RecipeUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RecipeUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *RecipeUpdateOne) sqlSave(ctx context.Context) (_node *Recipe, err error) {
	_spec := sqlgraph.NewUpdateSpec(recipe.Table, recipe.Columns, sqlgraph.NewFieldSpec(recipe.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Recipe.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, recipe.FieldID)
		for _, f := range fields {
			if !recipe.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != recipe.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(recipe.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(recipe.FieldDescription, field.TypeString, value)
	}
	if value, ok := _u.mutation.MealType(); ok {
		_spec.SetField(recipe.FieldMealType, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMealType(); ok {
		_spec.AddField(recipe.FieldMealType, field.TypeInt, value)
	}
	if _u.mutation.RecipeingredientCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   recipe.RecipeingredientTable,
			Columns: []string{recipe.RecipeingredientColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(recipeingredient.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedRecipeingredientIDs(); len(nodes) > 0 && !_u.mutation.RecipeingredientCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   recipe.RecipeingredientTable,
			Columns: []string{recipe.RecipeingredientColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(recipeingredient.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RecipeingredientIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   recipe.RecipeingredientTable,
			Columns: []string{recipe.RecipeingredientColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(recipeingredient.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Recipe{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{recipe.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
