// Code generated by ent, DO NOT EDIT.

package ent

import (
	"ch24/fakes/adapters/sqlaite/ent/predicate"
	"ch24/fakes/adapters/sqlaite/ent/recipeingredient"
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// RecipeIngredientDelete is the builder for deleting a RecipeIngredient entity.
type RecipeIngredientDelete struct {
	config
	hooks    []Hook
	mutation *RecipeIngredientMutation
}

// Where appends a list predicates to the RecipeIngredientDelete builder.
func (_d *RecipeIngredientDelete) Where(ps ...predicate.RecipeIngredient) *RecipeIngredientDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *RecipeIngredientDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *RecipeIngredientDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *RecipeIngredientDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(recipeingredient.Table, sqlgraph.NewFieldSpec(recipeingredient.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// RecipeIngredientDeleteOne is the builder for deleting a single RecipeIngredient entity.
type RecipeIngredientDeleteOne struct {
	_d *RecipeIngredientDelete
}

// Where appends a list predicates to the RecipeIngredientDelete builder.
func (_d *RecipeIngredientDeleteOne) Where(ps ...predicate.RecipeIngredient) *RecipeIngredientDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *RecipeIngredientDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{recipeingredient.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *RecipeIngredientDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
