// Code generated by ent, DO NOT EDIT.

package ent

import (
	"ch24/fakes/adapters/sqlite/ent/ingredient"
	"ch24/fakes/adapters/sqlite/ent/pantry"
	"ch24/fakes/adapters/sqlite/ent/predicate"
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// PantryQuery is the builder for querying Pantry entities.
type PantryQuery struct {
	config
	ctx            *QueryContext
	order          []pantry.OrderOption
	inters         []Interceptor
	predicates     []predicate.Pantry
	withIngredient *IngredientQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the PantryQuery builder.
func (_q *PantryQuery) Where(ps ...predicate.Pantry) *PantryQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *PantryQuery) Limit(limit int) *PantryQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *PantryQuery) Offset(offset int) *PantryQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *PantryQuery) Unique(unique bool) *PantryQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *PantryQuery) Order(o ...pantry.OrderOption) *PantryQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryIngredient chains the current query on the "ingredient" edge.
func (_q *PantryQuery) QueryIngredient() *IngredientQuery {
	query := (&IngredientClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(pantry.Table, pantry.FieldID, selector),
			sqlgraph.To(ingredient.Table, ingredient.FieldID),
			sqlgraph.Edge(sqlgraph.O2O, false, pantry.IngredientTable, pantry.IngredientColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first Pantry entity from the query.
// Returns a *NotFoundError when no Pantry was found.
func (_q *PantryQuery) First(ctx context.Context) (*Pantry, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{pantry.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *PantryQuery) FirstX(ctx context.Context) *Pantry {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Pantry ID from the query.
// Returns a *NotFoundError when no Pantry ID was found.
func (_q *PantryQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{pantry.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *PantryQuery) FirstIDX(ctx context.Context) int {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Pantry entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Pantry entity is found.
// Returns a *NotFoundError when no Pantry entities are found.
func (_q *PantryQuery) Only(ctx context.Context) (*Pantry, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{pantry.Label}
	default:
		return nil, &NotSingularError{pantry.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *PantryQuery) OnlyX(ctx context.Context) *Pantry {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Pantry ID in the query.
// Returns a *NotSingularError when more than one Pantry ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *PantryQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{pantry.Label}
	default:
		err = &NotSingularError{pantry.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *PantryQuery) OnlyIDX(ctx context.Context) int {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of Pantries.
func (_q *PantryQuery) All(ctx context.Context) ([]*Pantry, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*Pantry, *PantryQuery]()
	return withInterceptors[[]*Pantry](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *PantryQuery) AllX(ctx context.Context) []*Pantry {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Pantry IDs.
func (_q *PantryQuery) IDs(ctx context.Context) (ids []int, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(pantry.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *PantryQuery) IDsX(ctx context.Context) []int {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *PantryQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*PantryQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *PantryQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *PantryQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *PantryQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the PantryQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *PantryQuery) Clone() *PantryQuery {
	if _q == nil {
		return nil
	}
	return &PantryQuery{
		config:         _q.config,
		ctx:            _q.ctx.Clone(),
		order:          append([]pantry.OrderOption{}, _q.order...),
		inters:         append([]Interceptor{}, _q.inters...),
		predicates:     append([]predicate.Pantry{}, _q.predicates...),
		withIngredient: _q.withIngredient.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithIngredient tells the query-builder to eager-load the nodes that are connected to
// the "ingredient" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *PantryQuery) WithIngredient(opts ...func(*IngredientQuery)) *PantryQuery {
	query := (&IngredientClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withIngredient = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Quantity int `json:"quantity,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.Pantry.Query().
//		GroupBy(pantry.FieldQuantity).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *PantryQuery) GroupBy(field string, fields ...string) *PantryGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &PantryGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = pantry.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Quantity int `json:"quantity,omitempty"`
//	}
//
//	client.Pantry.Query().
//		Select(pantry.FieldQuantity).
//		Scan(ctx, &v)
func (_q *PantryQuery) Select(fields ...string) *PantrySelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &PantrySelect{PantryQuery: _q}
	sbuild.label = pantry.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a PantrySelect configured with the given aggregations.
func (_q *PantryQuery) Aggregate(fns ...AggregateFunc) *PantrySelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *PantryQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !pantry.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *PantryQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Pantry, error) {
	var (
		nodes       = []*Pantry{}
		_spec       = _q.querySpec()
		loadedTypes = [1]bool{
			_q.withIngredient != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Pantry).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Pantry{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withIngredient; query != nil {
		if err := _q.loadIngredient(ctx, query, nodes, nil,
			func(n *Pantry, e *Ingredient) { n.Edges.Ingredient = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *PantryQuery) loadIngredient(ctx context.Context, query *IngredientQuery, nodes []*Pantry, init func(*Pantry), assign func(*Pantry, *Ingredient)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*Pantry)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
	}
	query.withFKs = true
	query.Where(predicate.Ingredient(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(pantry.IngredientColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.pantry_ingredient
		if fk == nil {
			return fmt.Errorf(`foreign-key "pantry_ingredient" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "pantry_ingredient" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (_q *PantryQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *PantryQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(pantry.Table, pantry.Columns, sqlgraph.NewFieldSpec(pantry.FieldID, field.TypeInt))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, pantry.FieldID)
		for i := range fields {
			if fields[i] != pantry.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *PantryQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(pantry.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = pantry.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// PantryGroupBy is the group-by builder for Pantry entities.
type PantryGroupBy struct {
	selector
	build *PantryQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *PantryGroupBy) Aggregate(fns ...AggregateFunc) *PantryGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *PantryGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*PantryQuery, *PantryGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *PantryGroupBy) sqlScan(ctx context.Context, root *PantryQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// PantrySelect is the builder for selecting fields of Pantry entities.
type PantrySelect struct {
	*PantryQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *PantrySelect) Aggregate(fns ...AggregateFunc) *PantrySelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *PantrySelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*PantryQuery, *PantrySelect](ctx, _s.PantryQuery, _s, _s.inters, v)
}

func (_s *PantrySelect) sqlScan(ctx context.Context, root *PantryQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
