// Code generated by ent, DO NOT EDIT.

package ent

import (
	"ch24/fakes/adapters/sqlite/ent/ingredient"
	"ch24/fakes/adapters/sqlite/ent/pantry"
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// PantryCreate is the builder for creating a Pantry entity.
type PantryCreate struct {
	config
	mutation *PantryMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetQuantity sets the "quantity" field.
func (_c *PantryCreate) SetQuantity(v int) *PantryCreate {
	_c.mutation.SetQuantity(v)
	return _c
}

// SetIngredientID sets the "ingredient" edge to the Ingredient entity by ID.
func (_c *PantryCreate) SetIngredientID(id int) *PantryCreate {
	_c.mutation.SetIngredientID(id)
	return _c
}

// SetNillableIngredientID sets the "ingredient" edge to the Ingredient entity by ID if the given value is not nil.
func (_c *PantryCreate) SetNillableIngredientID(id *int) *PantryCreate {
	if id != nil {
		_c = _c.SetIngredientID(*id)
	}
	return _c
}

// SetIngredient sets the "ingredient" edge to the Ingredient entity.
func (_c *PantryCreate) SetIngredient(v *Ingredient) *PantryCreate {
	return _c.SetIngredientID(v.ID)
}

// Mutation returns the PantryMutation object of the builder.
func (_c *PantryCreate) Mutation() *PantryMutation {
	return _c.mutation
}

// Save creates the Pantry in the database.
func (_c *PantryCreate) Save(ctx context.Context) (*Pantry, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *PantryCreate) SaveX(ctx context.Context) *Pantry {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PantryCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PantryCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *PantryCreate) check() error {
	if _, ok := _c.mutation.Quantity(); !ok {
		return &ValidationError{Name: "quantity", err: errors.New(`ent: missing required field "Pantry.quantity"`)}
	}
	return nil
}

func (_c *PantryCreate) sqlSave(ctx context.Context) (*Pantry, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *PantryCreate) createSpec() (*Pantry, *sqlgraph.CreateSpec) {
	var (
		_node = &Pantry{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(pantry.Table, sqlgraph.NewFieldSpec(pantry.FieldID, field.TypeInt))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.Quantity(); ok {
		_spec.SetField(pantry.FieldQuantity, field.TypeInt, value)
		_node.Quantity = value
	}
	if nodes := _c.mutation.IngredientIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   pantry.IngredientTable,
			Columns: []string{pantry.IngredientColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ingredient.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Pantry.Create().
//		SetQuantity(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.PantryUpsert) {
//			SetQuantity(v+v).
//		}).
//		Exec(ctx)
func (_c *PantryCreate) OnConflict(opts ...sql.ConflictOption) *PantryUpsertOne {
	_c.conflict = opts
	return &PantryUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Pantry.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *PantryCreate) OnConflictColumns(columns ...string) *PantryUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &PantryUpsertOne{
		create: _c,
	}
}

type (
	// PantryUpsertOne is the builder for "upsert"-ing
	//  one Pantry node.
	PantryUpsertOne struct {
		create *PantryCreate
	}

	// PantryUpsert is the "OnConflict" setter.
	PantryUpsert struct {
		*sql.UpdateSet
	}
)

// SetQuantity sets the "quantity" field.
func (u *PantryUpsert) SetQuantity(v int) *PantryUpsert {
	u.Set(pantry.FieldQuantity, v)
	return u
}

// UpdateQuantity sets the "quantity" field to the value that was provided on create.
func (u *PantryUpsert) UpdateQuantity() *PantryUpsert {
	u.SetExcluded(pantry.FieldQuantity)
	return u
}

// AddQuantity adds v to the "quantity" field.
func (u *PantryUpsert) AddQuantity(v int) *PantryUpsert {
	u.Add(pantry.FieldQuantity, v)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.Pantry.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *PantryUpsertOne) UpdateNewValues() *PantryUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Pantry.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *PantryUpsertOne) Ignore() *PantryUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *PantryUpsertOne) DoNothing() *PantryUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the PantryCreate.OnConflict
// documentation for more info.
func (u *PantryUpsertOne) Update(set func(*PantryUpsert)) *PantryUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&PantryUpsert{UpdateSet: update})
	}))
	return u
}

// SetQuantity sets the "quantity" field.
func (u *PantryUpsertOne) SetQuantity(v int) *PantryUpsertOne {
	return u.Update(func(s *PantryUpsert) {
		s.SetQuantity(v)
	})
}

// AddQuantity adds v to the "quantity" field.
func (u *PantryUpsertOne) AddQuantity(v int) *PantryUpsertOne {
	return u.Update(func(s *PantryUpsert) {
		s.AddQuantity(v)
	})
}

// UpdateQuantity sets the "quantity" field to the value that was provided on create.
func (u *PantryUpsertOne) UpdateQuantity() *PantryUpsertOne {
	return u.Update(func(s *PantryUpsert) {
		s.UpdateQuantity()
	})
}

// Exec executes the query.
func (u *PantryUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for PantryCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *PantryUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *PantryUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *PantryUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// PantryCreateBulk is the builder for creating many Pantry entities in bulk.
type PantryCreateBulk struct {
	config
	err      error
	builders []*PantryCreate
	conflict []sql.ConflictOption
}

// Save creates the Pantry entities in the database.
func (_c *PantryCreateBulk) Save(ctx context.Context) ([]*Pantry, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Pantry, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PantryMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *PantryCreateBulk) SaveX(ctx context.Context) []*Pantry {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PantryCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PantryCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Pantry.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.PantryUpsert) {
//			SetQuantity(v+v).
//		}).
//		Exec(ctx)
func (_c *PantryCreateBulk) OnConflict(opts ...sql.ConflictOption) *PantryUpsertBulk {
	_c.conflict = opts
	return &PantryUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Pantry.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *PantryCreateBulk) OnConflictColumns(columns ...string) *PantryUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &PantryUpsertBulk{
		create: _c,
	}
}

// PantryUpsertBulk is the builder for "upsert"-ing
// a bulk of Pantry nodes.
type PantryUpsertBulk struct {
	create *PantryCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Pantry.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *PantryUpsertBulk) UpdateNewValues() *PantryUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Pantry.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *PantryUpsertBulk) Ignore() *PantryUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *PantryUpsertBulk) DoNothing() *PantryUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the PantryCreateBulk.OnConflict
// documentation for more info.
func (u *PantryUpsertBulk) Update(set func(*PantryUpsert)) *PantryUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&PantryUpsert{UpdateSet: update})
	}))
	return u
}

// SetQuantity sets the "quantity" field.
func (u *PantryUpsertBulk) SetQuantity(v int) *PantryUpsertBulk {
	return u.Update(func(s *PantryUpsert) {
		s.SetQuantity(v)
	})
}

// AddQuantity adds v to the "quantity" field.
func (u *PantryUpsertBulk) AddQuantity(v int) *PantryUpsertBulk {
	return u.Update(func(s *PantryUpsert) {
		s.AddQuantity(v)
	})
}

// UpdateQuantity sets the "quantity" field to the value that was provided on create.
func (u *PantryUpsertBulk) UpdateQuantity() *PantryUpsertBulk {
	return u.Update(func(s *PantryUpsert) {
		s.UpdateQuantity()
	})
}

// Exec executes the query.
func (u *PantryUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the PantryCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for PantryCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *PantryUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
