// Code generated by ent, DO NOT EDIT.

package ent

import (
	"ch24/fakes/adapters/sqlite/ent/ingredient"
	"ch24/fakes/adapters/sqlite/ent/predicate"
	"ch24/fakes/adapters/sqlite/ent/recipe"
	"ch24/fakes/adapters/sqlite/ent/recipeingredient"
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// RecipeIngredientUpdate is the builder for updating RecipeIngredient entities.
type RecipeIngredientUpdate struct {
	config
	hooks    []Hook
	mutation *RecipeIngredientMutation
}

// Where appends a list predicates to the RecipeIngredientUpdate builder.
func (_u *RecipeIngredientUpdate) Where(ps ...predicate.RecipeIngredient) *RecipeIngredientUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetQuantity sets the "quantity" field.
func (_u *RecipeIngredientUpdate) SetQuantity(v int) *RecipeIngredientUpdate {
	_u.mutation.ResetQuantity()
	_u.mutation.SetQuantity(v)
	return _u
}

// SetNillableQuantity sets the "quantity" field if the given value is not nil.
func (_u *RecipeIngredientUpdate) SetNillableQuantity(v *int) *RecipeIngredientUpdate {
	if v != nil {
		_u.SetQuantity(*v)
	}
	return _u
}

// AddQuantity adds value to the "quantity" field.
func (_u *RecipeIngredientUpdate) AddQuantity(v int) *RecipeIngredientUpdate {
	_u.mutation.AddQuantity(v)
	return _u
}

// SetRecipeID sets the "recipe" edge to the Recipe entity by ID.
func (_u *RecipeIngredientUpdate) SetRecipeID(id int) *RecipeIngredientUpdate {
	_u.mutation.SetRecipeID(id)
	return _u
}

// SetNillableRecipeID sets the "recipe" edge to the Recipe entity by ID if the given value is not nil.
func (_u *RecipeIngredientUpdate) SetNillableRecipeID(id *int) *RecipeIngredientUpdate {
	if id != nil {
		_u = _u.SetRecipeID(*id)
	}
	return _u
}

// SetRecipe sets the "recipe" edge to the Recipe entity.
func (_u *RecipeIngredientUpdate) SetRecipe(v *Recipe) *RecipeIngredientUpdate {
	return _u.SetRecipeID(v.ID)
}

// AddIngredientIDs adds the "ingredient" edge to the Ingredient entity by IDs.
func (_u *RecipeIngredientUpdate) AddIngredientIDs(ids ...int) *RecipeIngredientUpdate {
	_u.mutation.AddIngredientIDs(ids...)
	return _u
}

// AddIngredient adds the "ingredient" edges to the Ingredient entity.
func (_u *RecipeIngredientUpdate) AddIngredient(v ...*Ingredient) *RecipeIngredientUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddIngredientIDs(ids...)
}

// Mutation returns the RecipeIngredientMutation object of the builder.
func (_u *RecipeIngredientUpdate) Mutation() *RecipeIngredientMutation {
	return _u.mutation
}

// ClearRecipe clears the "recipe" edge to the Recipe entity.
func (_u *RecipeIngredientUpdate) ClearRecipe() *RecipeIngredientUpdate {
	_u.mutation.ClearRecipe()
	return _u
}

// ClearIngredient clears all "ingredient" edges to the Ingredient entity.
func (_u *RecipeIngredientUpdate) ClearIngredient() *RecipeIngredientUpdate {
	_u.mutation.ClearIngredient()
	return _u
}

// RemoveIngredientIDs removes the "ingredient" edge to Ingredient entities by IDs.
func (_u *RecipeIngredientUpdate) RemoveIngredientIDs(ids ...int) *RecipeIngredientUpdate {
	_u.mutation.RemoveIngredientIDs(ids...)
	return _u
}

// RemoveIngredient removes "ingredient" edges to Ingredient entities.
func (_u *RecipeIngredientUpdate) RemoveIngredient(v ...*Ingredient) *RecipeIngredientUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveIngredientIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *RecipeIngredientUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RecipeIngredientUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *RecipeIngredientUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RecipeIngredientUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *RecipeIngredientUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(recipeingredient.Table, recipeingredient.Columns, sqlgraph.NewFieldSpec(recipeingredient.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Quantity(); ok {
		_spec.SetField(recipeingredient.FieldQuantity, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedQuantity(); ok {
		_spec.AddField(recipeingredient.FieldQuantity, field.TypeInt, value)
	}
	if _u.mutation.RecipeCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   recipeingredient.RecipeTable,
			Columns: []string{recipeingredient.RecipeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(recipe.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RecipeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   recipeingredient.RecipeTable,
			Columns: []string{recipeingredient.RecipeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(recipe.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.IngredientCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   recipeingredient.IngredientTable,
			Columns: recipeingredient.IngredientPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ingredient.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedIngredientIDs(); len(nodes) > 0 && !_u.mutation.IngredientCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   recipeingredient.IngredientTable,
			Columns: recipeingredient.IngredientPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ingredient.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.IngredientIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   recipeingredient.IngredientTable,
			Columns: recipeingredient.IngredientPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ingredient.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{recipeingredient.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// RecipeIngredientUpdateOne is the builder for updating a single RecipeIngredient entity.
type RecipeIngredientUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *RecipeIngredientMutation
}

// SetQuantity sets the "quantity" field.
func (_u *RecipeIngredientUpdateOne) SetQuantity(v int) *RecipeIngredientUpdateOne {
	_u.mutation.ResetQuantity()
	_u.mutation.SetQuantity(v)
	return _u
}

// SetNillableQuantity sets the "quantity" field if the given value is not nil.
func (_u *RecipeIngredientUpdateOne) SetNillableQuantity(v *int) *RecipeIngredientUpdateOne {
	if v != nil {
		_u.SetQuantity(*v)
	}
	return _u
}

// AddQuantity adds value to the "quantity" field.
func (_u *RecipeIngredientUpdateOne) AddQuantity(v int) *RecipeIngredientUpdateOne {
	_u.mutation.AddQuantity(v)
	return _u
}

// SetRecipeID sets the "recipe" edge to the Recipe entity by ID.
func (_u *RecipeIngredientUpdateOne) SetRecipeID(id int) *RecipeIngredientUpdateOne {
	_u.mutation.SetRecipeID(id)
	return _u
}

// SetNillableRecipeID sets the "recipe" edge to the Recipe entity by ID if the given value is not nil.
func (_u *RecipeIngredientUpdateOne) SetNillableRecipeID(id *int) *RecipeIngredientUpdateOne {
	if id != nil {
		_u = _u.SetRecipeID(*id)
	}
	return _u
}

// SetRecipe sets the "recipe" edge to the Recipe entity.
func (_u *RecipeIngredientUpdateOne) SetRecipe(v *Recipe) *RecipeIngredientUpdateOne {
	return _u.SetRecipeID(v.ID)
}

// AddIngredientIDs adds the "ingredient" edge to the Ingredient entity by IDs.
func (_u *RecipeIngredientUpdateOne) AddIngredientIDs(ids ...int) *RecipeIngredientUpdateOne {
	_u.mutation.AddIngredientIDs(ids...)
	return _u
}

// AddIngredient adds the "ingredient" edges to the Ingredient entity.
func (_u *RecipeIngredientUpdateOne) AddIngredient(v ...*Ingredient) *RecipeIngredientUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddIngredientIDs(ids...)
}

// Mutation returns the RecipeIngredientMutation object of the builder.
func (_u *RecipeIngredientUpdateOne) Mutation() *RecipeIngredientMutation {
	return _u.mutation
}

// ClearRecipe clears the "recipe" edge to the Recipe entity.
func (_u *RecipeIngredientUpdateOne) ClearRecipe() *RecipeIngredientUpdateOne {
	_u.mutation.ClearRecipe()
	return _u
}

// ClearIngredient clears all "ingredient" edges to the Ingredient entity.
func (_u *RecipeIngredientUpdateOne) ClearIngredient() *RecipeIngredientUpdateOne {
	_u.mutation.ClearIngredient()
	return _u
}

// RemoveIngredientIDs removes the "ingredient" edge to Ingredient entities by IDs.
func (_u *RecipeIngredientUpdateOne) RemoveIngredientIDs(ids ...int) *RecipeIngredientUpdateOne {
	_u.mutation.RemoveIngredientIDs(ids...)
	return _u
}

// RemoveIngredient removes "ingredient" edges to Ingredient entities.
func (_u *RecipeIngredientUpdateOne) RemoveIngredient(v ...*Ingredient) *RecipeIngredientUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveIngredientIDs(ids...)
}

// Where appends a list predicates to the RecipeIngredientUpdate builder.
func (_u *RecipeIngredientUpdateOne) Where(ps ...predicate.RecipeIngredient) *RecipeIngredientUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *RecipeIngredientUpdateOne) Select(field string, fields ...string) *RecipeIngredientUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated RecipeIngredient entity.
func (_u *RecipeIngredientUpdateOne) Save(ctx context.Context) (*RecipeIngredient, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RecipeIngredientUpdateOne) SaveX(ctx context.Context) *RecipeIngredient {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *RecipeIngredientUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RecipeIngredientUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *RecipeIngredientUpdateOne) sqlSave(ctx context.Context) (_node *RecipeIngredient, err error) {
	_spec := sqlgraph.NewUpdateSpec(recipeingredient.Table, recipeingredient.Columns, sqlgraph.NewFieldSpec(recipeingredient.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "RecipeIngredient.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, recipeingredient.FieldID)
		for _, f := range fields {
			if !recipeingredient.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != recipeingredient.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Quantity(); ok {
		_spec.SetField(recipeingredient.FieldQuantity, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedQuantity(); ok {
		_spec.AddField(recipeingredient.FieldQuantity, field.TypeInt, value)
	}
	if _u.mutation.RecipeCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   recipeingredient.RecipeTable,
			Columns: []string{recipeingredient.RecipeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(recipe.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RecipeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   recipeingredient.RecipeTable,
			Columns: []string{recipeingredient.RecipeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(recipe.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.IngredientCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   recipeingredient.IngredientTable,
			Columns: recipeingredient.IngredientPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ingredient.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedIngredientIDs(); len(nodes) > 0 && !_u.mutation.IngredientCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   recipeingredient.IngredientTable,
			Columns: recipeingredient.IngredientPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ingredient.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.IngredientIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   recipeingredient.IngredientTable,
			Columns: recipeingredient.IngredientPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ingredient.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &RecipeIngredient{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{recipeingredient.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
